accepted = ["MIT", "Apache-2.0", "BSD-3-Clause", "BSD-2-Clause", "0BSD", "ISC", "Zlib", "Unicode-3.0", "BSL-1.0", "CC0-1.0", "Unlicense", "LicenseRef-Slint-Royalty-free-2.0"]
targets = ["x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu", "x86_64-apple-darwin", "aarch64-apple-darwin"]
ignore-dev-dependencies = true

[i-slint-backend-selector.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"
[[i-slint-backend-selector.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[i-slint-backend-winit.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"
[[i-slint-backend-winit.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[i-slint-common.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"
[[i-slint-common.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[i-slint-compiler.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"
[[i-slint-compiler.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[i-slint-core.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"
[[i-slint-core.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[i-slint-core-macros.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"
[[i-slint-core-macros.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[i-slint-renderer-femtovg.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"
[[i-slint-renderer-femtovg.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[slint.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"
[[slint.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[slint-build.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"
[[slint-build.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"

[slint-macros.clarify]
license = "LicenseRef-Slint-Royalty-free-2.0"
[[slint-macros.clarify.files]]
path = "LICENSES/LicenseRef-Slint-Royalty-free-2.0.md"
checksum = "5167f5056e850419106ab6265efbdca7cba4d99c849d1445ca0bbf6a1e2315fe"
